### ISSUE TITLE
LeaseDuration - unhandled exception, when get the property on some scopes

### ISSUE THREAD

**Issue by Csontikka** [garysharp/DhcpServerApi#11]
Hi!

If you set the leasing time of a scope to "0day, 0 hour, 0 minutes", when you try to read the scope-LeaseDuration property, you get an unhandled exception. (Dhcp.DhcpServerException)

Please help if i am wrong or there is a bug in the API.

Thanks,
Regards,
Csontikka

**Comment by garysharp** [comment]
I was not able to reproduce the behaviour. The DHCP UI (on Server 2012 R2) did not allow me to set the lease duration to "0 days, 0 hours, 0 minutes."
![image](https://user-images.githubusercontent.com/1687386/54801090-57f75b00-4cb9-11e9-92ec-424a2aadd7ad.png)

Interestingly setting the lease duration to Unlimited results in a TimeSpan value of -1 second. I've added #12 with a proposal to change this in the future.

@Csontikka would you be able to provide some more information on the exception? The exception `Message` would be very helpful as it contains the Win32 API function which caused the error. A stack-trace would also be useful.

**Comment by garysharp** [comment]
Also confirmed the same behaviour as above (`You must specify a lease duration.`) on Server 2016 (thanks Rohan).

**Comment by garysharp** [comment]
Hi @Csontikka - please reopen this issue when you have more information.

**Comment by Csontikka** [comment]
Thanks for investigation!
I asked the operation team to eliminate these scopes, so now it is is working fine.

btw, I don't know how they created scopes with null leaseing time, (Maybe with PowerShell you can add scope without lease duration, but i have not tested it.)

**Comment by garysharp** [comment]
Thanks @Csontikka - that's interesting. I wonder what the behaviour of those scopes would have been? I'm not sure what purpose an IP address with a zero second lease time would have.
