### ISSUE TITLE
Unable to impersonate user

### ISSUE THREAD

**Issue by los93sol** [garysharp/DhcpServerApi#2]
I'm trying to impersonate a user so that I can pass in custom credentials when authenticating to the DHCP server, but it appears to ignore the impersonation context in most cases.  It would be excellent if I could simply pass credentials in when calling Connect

**Comment by garysharp** [comment]
The main aim of this project is to create a managed wrapper around the [DHCP Server Management API](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363376%28v=vs.85%29.aspx) ([see signatures](https://github.com/garysharp/DhcpServerApi/blob/master/src/Dhcp/Native/Api.cs)).
Unfortunately these APIs don't include a way to connect to a DHCP instance with credentials.

I was able to successfully run the [DhcpDemo](https://github.com/garysharp/DhcpServerApi/blob/master/src/DhcpDemo/Program.cs) (which covers most functions) impersonating another user by wrapping the demo using the example code found in the [WindowsIdentity.Impersonate()](https://msdn.microsoft.com/en-us/library/w070t6ka%28v=vs.110%29.aspx?cs-lang=csharp#code-snippet-2) MSDN documentation.

**Comment by los93sol** [comment]
I took a closer look at what was happening and it appears my issue was actually related to the fact that I was resolving a hostname to an ip and passing the ip to the Connect function.  The issue was both IPv4 and IPv6 were enabled and I was not checking that I passed the IPv4 address so it was erroring on the IPv6 address.
