### ISSUE TITLE
can not add option value to reservation

### ISSUE THREAD

**Issue by AboveNBeyondCode** [garysharp/DhcpServerApi#30]
Hello,

I am trying to add a Option Value to a new created reservation, but I am always getting an access violation. I tried both ways as below both times I get the violation.

Can anybody explain me, why this error occurs?

```
var dhcpServer = DhcpServer.Connect(192.168.0.1);
var scope = dhcpServer.Scopes.First();
var NewReservation = scope.Reservations.AddReservation("192.168.0.10", "AA:BB:CC:DD:EE:FF");
NewReservation.Client.Name = "Demo";
var Option67 = dhcpServer.Options.GetDefaultOption(67);
var ReservationOption67 = Option67.CreateOptionStringValue("demo");
NewReservation.Options.AddOrSetOptionValue(Option67);

NewReservation.Options.SetOptionValue(dhcpServer.Options.GetDefaultOption(67).CreateOptionStringValue("DEMO"));
```

**Comment by garysharp** [comment]
I haven't been able to reproduce the error.

The sample code you provided must have been modified before posting (perhaps to anonymize?):
1. The first line is missing quotes around the specified IP address.
2. `AddOrSetOptionValue` (line 7) cannot receive variable `Option67` (of type `IDhcpServerOption`) as a parameter; I guess `ReservationOption67` (`IDhcpServerOptionValue`) was intended.

Without correcting those mistakes the code would not build (let alone throw an access violation).
After adjusting however, the code does build, and (in my environment) runs successfully.

```c#
var dhcpServer = DhcpServer.Connect("YourServerAddress");
var scope = dhcpServer.Scopes.First();
var NewReservation = scope.Reservations.AddReservation("ClientAddressWithinScopeRange", "AA:BB:CC:DD:EE:FF");
NewReservation.Client.Name = "Demo";
var Option67 = dhcpServer.Options.GetDefaultOption(67);
var ReservationOption67 = Option67.CreateOptionStringValue("demo");
NewReservation.Options.AddOrSetOptionValue(ReservationOption67);
```

Some more information will be needed to diagnose.
1. Which version of the DhcpServerApi library are you using?
2. Which version of Windows Server are you targeting?
3. Which version of .NET are you using?
4. Is you app running as 32 or 64-bit?
5. Please provide an exception stack-trace, and the full error message.

**Comment by AboveNBeyondCode** [comment]
Hi,
here the needed answers:

yes the missing "" and the other wrong value happed due to anonymising.
I tried the code, you posted - still getting the error.

1. 1.0.2 alpha
2. Windows Server 2016
3. .Net 4.5 (tried 4.5.2 same error)
4. set to any CPU
5. 
`System.AccessViolationException was unhandled.
 HResult=-2147467261
 Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
 Source=DhcpServerApi
 StackTrace:
      bei Dhcp.Native.Api.DhcpSetOptionValueV5(String ServerIpAddress, UInt32 Flags, Int32 OptionID, String ClassName, String VendorName, IntPtr ScopeInfo, DHCP_OPTION_DATA_Managed OptionValue)
      bei Dhcp.DhcpServerOptionValue.SetOptionValueV5(DhcpServer server, IntPtr scopeInfo, Int32 optionId, String className, String vendorName, IEnumerable`1 values)
      bei Dhcp.DhcpServerOptionValue.SetOptionValue(DhcpServer server, IntPtr scopeInfo, Int32 optionId, String className, String vendorName, IEnumerable`1 values)
      bei Dhcp.DhcpServerOptionValue.SetScopeReservationOptionValue(DhcpServer server, DhcpServerIpAddress scopeAddress, DhcpServerIpAddress reservationAddress, Int32 optionId, String className, String vendorName, IEnumerable`1 values)
      bei Dhcp.DhcpServerOptionValue.SetScopeReservationOptionValue(DhcpServerScopeReservation reservation, Int32 optionId, String className, String vendorName, IEnumerable`1 values)
      bei Dhcp.DhcpServerOptionValue.SetScopeReservationOptionValue(DhcpServerScopeReservation reservation, DhcpServerOptionValue optionValue)
      bei Dhcp.DhcpServerScopeReservationOptionValueCollection.AddOrSetOptionValue(IDhcpServerOptionValue value)
      bei DHCPSET._Default.Button1_Click(Object sender, EventArgs e) in z:\Visual Studio\DHCPSET\DHCPSET\Default.aspx.cs:Zeile 369.
      bei System.Web.UI.WebControls.Button.OnClick(EventArgs e)
      bei System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
      bei System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
      bei System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
      bei System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
      bei System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
      bei System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
      bei System.Web.UI.Page.ProcessRequest()
      bei System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
      bei System.Web.UI.Page.ProcessRequest(HttpContext context)
      bei ASP.default_aspx.ProcessRequest(HttpContext context) in c:\Users\user01\AppData\Local\Temp\2\Temporary ASP.NET Files\vs\6a55e114\2c3fbbe3\App_Web_1qiifnuq.1.cs:Zeile 0.
      bei System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
      bei System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
      bei System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
      bei System.Web.HttpApplication.ApplicationStepManager.ResumeSteps(Exception error)
      bei System.Web.HttpApplication.System.Web.IHttpAsyncHandler.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object extraData)
      bei System.Web.HttpRuntime.ProcessRequestInternal(HttpWorkerRequest wr)
      bei System.Web.HttpRuntime.ProcessRequestNoDemand(HttpWorkerRequest wr)
      bei System.Web.HttpRuntime.ProcessRequest(HttpWorkerRequest wr)
      bei Microsoft.VisualStudio.WebHost.Request.Process()
      bei Microsoft.VisualStudio.WebHost.Host.ProcessRequest(Connection conn)
      bei Microsoft.VisualStudio.WebHost.Host.ProcessRequest(Connection conn)
      bei Microsoft.VisualStudio.WebHost.Server.OnSocketAccept(Object acceptedSocket)
      bei System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
      bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
      bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
      bei System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
      bei System.Threading.ThreadPoolWorkQueue.Dispatch()
      bei System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
 InnerException:`

**Comment by garysharp** [comment]
Thank you for the information. I believe your application (regardless of your hardware/OS) is running in 32-bit mode. It is likely the 'Prefer 32-bit' option is selected. While I hope 32-bit applications will work, testing of this library is largely restricted to 64-bit applications. 

With the information you provided I was able to narrow down the 32/64-bit compatibility difference 897421ba1a531f70675de5ae2b2e5ad7709926c3. 

I've released an alpha build including this change:
https://www.nuget.org/packages/DhcpServerApi/1.0.3-alpha

Please test and let me know your result.

**Comment by AboveNBeyondCode** [comment]
Thank you.

I used the new 1.0.3 NuGet-Package and it worked like a charm.
