### ISSUE TITLE
Exception thrown enumerating ExcludedIpRanges in scope

### ISSUE THREAD

**Issue by los93sol** [garysharp/DhcpServerApi#4]
An exception is thrown when iterating ExcludedIpRanges for a scope in the demo console application.  This only happens when the scope does not have any ExcludedIpRanges.  I'm actually not sure if the exception should be swallowed by the API and just return 0 objects to the caller or if it should bubble the exception.  This seems like one of the rare cases where swallowing the exception might be the appropriate thing to do to avoid messy try/catches in calling code.

**Comment by garysharp** [comment]
Absolutely correct, this function was meant to return 0 objects [when no excluded IP ranges were present](https://github.com/garysharp/DhcpServerApi/blob/84541836e594ef236a77c3731f88698fc554d850/src/Dhcp/DhcpServerScope.cs#L230) for a particular scope. It seems [an additional check was introduced](https://github.com/garysharp/DhcpServerApi/blob/84541836e594ef236a77c3731f88698fc554d850/src/Dhcp/DhcpServerScope.cs#L227) to early (for what reason I don't know - probably an oversight). This additional check was removed in a7b6d0a415b79c530e70862f1f06f7ea4759485f as the check is [already present later in the method](https://github.com/garysharp/DhcpServerApi/blob/84541836e594ef236a77c3731f88698fc554d850/src/Dhcp/DhcpServerScope.cs#L233).

**Comment by los93sol** [comment]
Thank you again for such an outstanding lib.  Any chance you can publish an updated Nuget package with the latest fixes?

**Comment by garysharp** [comment]
[Done](https://www.nuget.org/packages/DhcpServerApi/0.3.0). Might take a few minutes for NuGet to index. Glad its being used. Keep the feedback coming.
