### ISSUE TITLE
.net 5,.net 6 target  support

### ISSUE THREAD

**Issue by sgf** [garysharp/DhcpServerApi#43]
.net 5,.net 6 target not support now

**Comment by garysharp** [comment]
Work was completed to support .net core (now .net 5+). The Callout functionality was [pulled into a separate library](https://www.nuget.org/packages/DhcpServerApi.Callout/) which still requires .net framework. The core functionality [prerelease package](https://www.nuget.org/packages/DhcpServerApi/1.0.10-alpha) support [netstandard2.0](https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/#what-you-should-target).

```PowerShell
Install-Package DhcpServerApi -IncludePrerelease
```

**Comment by sgf** [comment]
👍
