### ISSUE TITLE
Write capability

### ISSUE THREAD

**Issue by clefranc** [garysharp/DhcpServerApi#5]
Hi,
I need to modify the reservation option 67 (bootfile name) from my Web app.

Do you think it's possible to add this function to your .Net API?

BTW, great work, a little gem for DHCP managers, easy to use and program.

**Comment by clefranc** [comment]
@garysharp

**Comment by garysharp** [comment]
Hi @clefranc,

It would be fantastic to add write capabilities to this library. The original focus was limited to extracting information (which was what I needed for a project at the time). It would be good to give the implementation of this some thought. I'm sure it wouldn't be terribly difficult to initially add write capabilities limited to the area you need.

Unfortunately I'm incredibly busy on another time-sensitive project at the moment. It will be at least a few weeks before I can pick this project up.

Any feedback, suggestions and especially pull requests on this would be greatly appreciated.

**Comment by clefranc** [comment]
@garysharp,
I am a patient man!

Really, I would like to participate into this project, but alas, I'm a casual VB programmer.

I will be nonetheless available to help test a writable version when time come.

Thank you

**Comment by clefranc** [comment]
@garysharp,
Any development on this?

**Comment by clefranc** [comment]
@garysharp ?

**Comment by clefranc** [comment]
@garysharp

**Comment by clefranc** [comment]
@garysharp What's the status of the write capability?

**Comment by steffenschumacher** [comment]
@garysharp I also need write, and I might reasonably able to pay for your time if its feasible within the next month or so?

**Comment by garysharp** [comment]
@steffenschumacher can we take this conversation offline? What is your email address?

**Comment by steffenschumacher** [comment]
stsmr - vestas.com..

**Comment by garysharp** [comment]
Thanks @steffenschumacher - email sent.

**Comment by clefranc** [comment]
@garysharp Include me too please, I'm sure I can contribute honestly.

**Comment by garysharp** [comment]
@clefranc - happy to include you. What is your email address?

**Comment by clefranc** [comment]
***removed***

**Comment by garysharp** [comment]
Thanks @clefranc - email sent.

**Comment by garysharp** [comment]
This task is being migrated into [Version 1.0 Project](https://github.com/garysharp/DhcpServerApi/projects/1)
