### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ThiloL** [garysharp/DhcpServerApi#6]
It would be fine to work also with 3rd-party dhcp servers.
i. e. http://www.n3k.de/produkte/ip-management/runip/runip-managed-dns-dhcp-appliance/

**Comment by garysharp** [comment]
Thanks for your interest in the project @ThiloL 

This library is primarily a .NET wrapper around the [native Win32 API's exposed by Microsoft's DHCP Server](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363376(v=vs.85).aspx). The structure of the libraries public surface area (its classes, properties, methods, etc) is heavily influenced by the architecture of these Win32 APIs.
Personally, I have no desire to expand the library to support other DHCP Server implementations. It seems to me that such an endeavour would most likely be done in a separate project. However I'm not against the idea in principle.

If you would like to build the abstraction layer and implement a third-party API I encourage you to submit a pull-request. If you intend to do so I encourage you to further outline your plans in this thread first to avoid any issues later on. You might want to consider (among other things):
- efforts to maintain compatibility for existing users
- an abstraction which would allow any server to be implemented
- how to deal with dependencies (ie. a rest-api might require a HTTP client library and json support; but these dependencies would be prohibitive for a user just wanting Microsoft DHCP Server support)

I look forward to hearing your thoughts on this.
