### ISSUE TITLE
Issue in syntax

### ISSUE THREAD

**Issue by arnaudhelin-zz** [garysharp/DhcpServerApi#7]
Hi,

You wrote this on the readme:

// Connect to DHCP Server
var dhcpServer = DhcpServer.Servers.First();

// Display scope information
foreach (var scope in dhcpServer.Scopes)
{
    Console.WriteLine("Scope: ", scope.Name);
    Console.WriteLine("  Address: ", scope.Address);
    Console.WriteLine("  Mask: ", scope.Mask);
    Console.WriteLine("  Range: ", scope.IpRange);
    Console.WriteLine("  State: ", scope.State);
}

But there is an issue, it should be:

// Connect to DHCP Server
var dhcpServer = DhcpServer.Servers.First();

// Display scope information
foreach (var scope in dhcpServer.Scopes)
{
    Console.WriteLine("Scope: {0}", scope.Name);
    Console.WriteLine("  Address: {0}", scope.Address);
    Console.WriteLine("  Mask: {0}", scope.Mask);
    Console.WriteLine("  Range: {0}", scope.IpRange);
    Console.WriteLine("  State: {0}", scope.State);
}

Hope it helps,

Arnaud H.

**Comment by garysharp** [comment]
Fixed in development branch

**Comment by garysharp** [comment]
Thanks @arnaudhelin
