### ISSUE TITLE
DhcpServerClientAddressStates - WRONG VALUES!!

### ISSUE THREAD

**Issue by TrevorWesterdahl** [garysharp/DhcpServerApi#9]
Nearly all the "AddressState" information I receive from this API is wrong. The API infers that there is a simple enumeration of five states. This is not so....

Please see link:
https://social.technet.microsoft.com/Forums/en-US/4e6e1313-2743-462f-94a2-f95a6b312bbd/dhcp-lease-address-state-values?forum=winserverPN

Unfortunately, this API is masking the real "byte" value of the true Address State and returns bad values that cannot be correctly interpretted

As an immediate fix... please provide the Raw/native byte value as the Address State is really supplying multiple states/values in one field based on corresponding bit values within the byte (again see link for details).

**Comment by TrevorWesterdahl** [comment]
The problem is that the AddressState should be a flags enum. I created my own and cast to it to get the correct values. NOTE: A lease is not necessarily active just because the active flag is set. The Active flag can be set to true, but if the Doomed flag is also set to true, the lease is not active and the entry won;t show up in the DHCP listing.

Here is the enum:
        [Flags]
        public enum AddressStateFlagged
        {
            /// <summary>
            /// The DHCPv4 client has been offered this IPv4 address.
            /// </summary>
            Offered = 0x00,
            /// <summary>
            /// The IPv4 address is active and has an active DHCPv4 client lease record.
            /// </summary>
            Active = 0x01,
            /// <summary>
            /// The IPv4 address request was declined by the DHCPv4 client; hence, it is a bad IPv4 address.
            /// </summary>
            Declined = 0x02,
            /// <summary>
            /// The IPv4 address is in DOOMED state and is due to be deleted.
            /// </summary>
            Doomed = 0x03,
            /// <summary>
            /// DHCID Part1 and two are two flags that have meaning together. If Part1 and Part2 are false, then DHCID is not in use. 
            /// If Part1 is true, and Part2 is false, then DHCID version 3.5.3 is in use. If Part1 is false and Part2 is true, the version 3.5.2 is in use. 
            /// If Part1 is thrue and Part2 is true, then version 3.5.1 is in use.
            /// </summary>
            DHCIDPart1 = 0x04,
            /// <summary>
            /// DHCID Part1 and two are two flags that have meaning together. If Part1 and Part2 are false, then DHCID is not in use. 
            /// If Part1 is true, and Part2 is false, then DHCID version 3.5.3 is in use. If Part1 is false and Part2 is true, the version 3.5.2 is in use. 
            /// If Part1 is thrue and Part2 is true, then version 3.5.1 is in use.
            /// </summary>
            DHCIDPart2 = 0x08,
            /// <summary>
            /// The DNS update for the DHCPv4 client lease record needs to be deleted from the DNS server when the lease is deleted
            /// </summary>
            DNSNeedsDeletion = 0x10,
            /// <summary>
            /// The DNS update needs to be sent for both A and PTR resource records
            /// </summary>
            DNSNeedsUpdate = 0x20,
            /// <summary>
            /// The DNS update is not completed for the lease record.
            /// </summary>
            DNSUpdateNotCompleted = 0x40,
            /// <summary>
            /// The address lease is expired, but the DNS updates for the lease record have not been deleted from the DNS server
            /// </summary>
            ExpiredLeaseNotDeletedFromDNS = 0x80,
            /// <summary>
            /// For backwards-compatibility
            /// </summary>
            Unknown = 0x100
        }

**Comment by garysharp** [comment]
Thanks @TrevorWesterdahl - some of the Win32 documentation can be a little difficult to interpret sometimes. 
https://docs.microsoft.com/en-us/windows/desktop/api/dhcpsapi/ns-dhcpsapi-dhcp_client_info_v5

https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-dhcpm/6a445cf3-6e6c-4e29-9817-ac78adc50336

Fixed in 7c52eb2
